stages:
  - stop_app   # Этап для остановки запущенного приложения
  - install_deps  # Этап для установки зависимостей
  - start_app  # Этап для запуска приложения

# Этап остановки приложения
stop_app:
  stage: stop_app
  tags:
    - spitec
  script:
    # Завершение запущенной программы, если она существует
    - |
      if [ -f "/tmp/gunicorn.pid" ]; then
        kill -9 $(cat /tmp/gunicorn.pid) || true
        rm /tmp/gunicorn.pid
      fi
  only:
    - main

# Этап установки зависимостей
install_deps:
  stage: install_deps
  tags:
    - spitec
  script:
    - poetry install
  only:
    - main

# Этап запуска приложения
start_app:
  stage: start_app
  tags:
    - spitec
  script:
    - |
      if [ ! -d "./logging" ]; then
        mkdir logging
      fi
    - nohup poetry run gunicorn -w 4 -b 0.0.0.0:8050 --pid /tmp/gunicorn.pid main:server > ./logging/log.txt 2>&1 &
    # Ждём, пока PID-файл не будет создан. Это означает, что приложение запустилось
    - |
      COUNTER=0
      while [ ! -f /tmp/gunicorn.pid ]; do
        if [ $COUNTER -ge 15 ]; then
          exit 1
        fi
        sleep 1
        COUNTER=$((COUNTER+1))
      done
    - sleep 10
  only:
    - main
  artifacts:
    paths:
      - ./logging/log.txt
    expire_in: 1 week  