name: Deploy SPITEC

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install SSH Key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        ssh-keyscan 51.250.35.185 >> ~/.ssh/known_hosts

    - name: Test Connection
      run: ssh -i ~/.ssh/id_ed25519 albert@51.250.35.185 hostname

    - name: Deploy Application
      run: |
        ssh -i ~/.ssh/id_ed25519 albert@51.250.35.185 "
          cd ~/spitec
          git fetch --all
          git reset --hard origin/main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart spitec
        "
