name: Deploy SPITEC

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Configure known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: ssh -T deployer@158.160.154.125

    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 158.160.154.125
        username: deployer
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/albert/spitec
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart spitec'
