name: Deploy SPITEC

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no deployer@158.160.154.125 << 'EOF'
        cd /home/albert/spitec
        git pull origin main
        source venv/bin/activate
        pip install -r requirements.txt
        sudo systemctl restart spitec
        EOF
